package bible

const (
	KRV_FILE     = "KRV.SQLite3"
	ESV_FILE     = "ESV.SQLite3"
	KRV_BOOK_ONE = 1  // number of first book on KRV
	ESV_BOOK_ONE = 10 // number of first book on ESV
)

type Bible interface {
	Init(version string)
	Fetch()
	Generate()
}

type Entry struct {
	Verse   int32  `db:"verse"`
	Content string `db:"content"`
}

type Input struct {
	Title    string
	Memories []string
	Verses   []string
}

var (
	BooksByNumber = map[int]string{
		1:  "창세기,Genesis",
		2:  "출애굽기,Exodus",
		3:  "레위기,Leviticus",
		4:  "민수기,Numbers",
		5:  "신명기,Deuteronomy",
		6:  "여호수아,Joshua",
		7:  "사사기,Judges",
		8:  "룻기,Ruth",
		9:  "사무엘상,1 Samuel",
		10: "사무엘하,2 Samuel",
		11: "열왕기상,1 Kings",
		12: "열왕기하,2 Kings",
		13: "역대상,1 Chronicles",
		14: "역대하,2 Chronicles",
		15: "에스라,Ezsa",
		16: "느헤미야,Nehemiah,",
		17: "에스더,Esther",
		18: "욥기,Job",
		19: "시편,Psalms",
		20: "잠언,Proverbs",
		21: "전도서,Ecclesiastes",
		22: "아가,Song of Solomon",
		23: "이사야,Isaiah",
		24: "예레미야,Jeremiah",
		25: "예레미야애가,Lamentations",
		26: "에스겔,Ezekiel",
		27: "다니엘,Daniel",
		28: "호세아,Hosea",
		29: "요엘,Joel",
		30: "아모스,Amos",
		31: "오바댜,Obadiah",
		32: "요나,Jonah",
		33: "미가,Micah",
		34: "나훔,Nahum",
		35: "하박국,Habakkuk",
		36: "스바냐,Zephaniah",
		37: "학개,Haggai",
		38: "스가랴,Zechariah",
		39: "말라기,Malachi",
		40: "마태복음,Matthew",
		41: "마가복음,Mark",
		42: "누가복음,Luke",
		43: "요한복음,John",
		44: "사도행전,Acts of the Apostles",
		45: "로마서,Romans",
		46: "고린도전서,1 Corinthians",
		47: "고린도후서,2 Corinthians",
		48: "갈라디아서,Galatians",
		49: "에베소서,Ephesians",
		50: "빌립보서,Philippians",
		51: "골로새서,Colossians",
		52: "데살로니가전서,1 Thessalonians",
		53: "데살로니가후서,2 Thessalonians",
		54: "디모데전서,1 Timothy",
		55: "디모데후서,2 Timothy",
		56: "디도서,Titus",
		57: "빌레몬서,Philemon",
		58: "히브리서,Hebrews",
		59: "야고보서,James",
		60: "베드로전서,1 Peter",
		61: "베드로후서,2 Peter",
		62: "요한1서,1 John",
		63: "요한2서,2 John",
		64: "요한3서,3 John",
		65: "유다서,Jude",
		66: "요한계시록,Revelation",
	}

	BooksByName = map[string]int{
		"창":              1,
		"출":              2,
		"레":              3,
		"민":              4,
		"신":              5,
		"수":              6,
		"삿":              7,
		"삼상":             9,
		"삼하":             10,
		"왕상":             11,
		"왕하":             12,
		"대상":             13,
		"대하":             14,
		"스":              15,
		"느":              16,
		"에":              17,
		"욥":              18,
		"시":              19,
		"잠":              20,
		"전":              21,
		"아":              22,
		"사":              23,
		"렘":              24,
		"애":              25,
		"겔":              26,
		"단":              27,
		"호":              28,
		"욜":              29,
		"암":              30,
		"옵":              31,
		"욘":              32,
		"미":              33,
		"나":              34,
		"합":              35,
		"습":              36,
		"학":              37,
		"슥":              38,
		"말":              39,
		"마":              40,
		"막":              41,
		"눅":              42,
		"요":              43,
		"행":              44,
		"롬":              45,
		"고전":             46,
		"고후":             47,
		"갈":              48,
		"엡":              49,
		"빌":              50,
		"골":              51,
		"살전":             52,
		"살후":             53,
		"딤전":             54,
		"딤후":             55,
		"딛":              56,
		"몬":              57,
		"히":              58,
		"약":              59,
		"벧전":             60,
		"벧후":             61,
		"요일":             62,
		"요이":             63,
		"요삼":             64,
		"유":              65,
		"계":              66,
		"genesis":        1,
		"gen":            1,
		"exodus":         2,
		"exo":            2,
		"leviticus":      3,
		"lev":            3,
		"numbers":        4,
		"num":            4,
		"deuteronomy":    5,
		"deut":           5,
		"joshua":         6,
		"josh":           6,
		"judges":         7,
		"judg":           7,
		"ruth":           8,
		"1sam":           9,
		"2sam":           10,
		"1kings":         11,
		"1kgs":           11,
		"2kings":         12,
		"2kgs":           12,
		"1chronicles":    13,
		"1chron":         13,
		"2chronicles":    14,
		"2chron":         14,
		"ezra":           15,
		"nehemiah":       16,
		"neh":            16,
		"esther":         17,
		"esth":           16,
		"job":            18,
		"psalms":         19,
		"ps":             19,
		"proverbs":       20,
		"prov":           20,
		"ecclesiastes":   21,
		"eccl":           21,
		"song":           22,
		"isaiah":         23,
		"isa":            23,
		"jeremiah":       24,
		"jer":            24,
		"lamentations":   25,
		"lam":            25,
		"ezekiel":        26,
		"ezek":           26,
		"daniel":         27,
		"dan":            27,
		"hosea":          28,
		"hos":            28,
		"joel":           29,
		"amos":           30,
		"obadiah":        31,
		"obad":           31,
		"jonah":          32,
		"micah":          33,
		"mic":            33,
		"nahum":          34,
		"nah":            34,
		"habakkuk":       35,
		"hab":            35,
		"zephaniah":      36,
		"zep":            36,
		"haggai":         37,
		"hag":            37,
		"zechariah":      38,
		"zech":           38,
		"zec":            38,
		"malachi":        39,
		"mal":            39,
		"matthew":        40,
		"matt":           40,
		"mat":            40,
		"mark":           41,
		"luke":           42,
		"john":           43,
		"acts":           44,
		"romans":         45,
		"rom":            45,
		"1corinthians":   46,
		"1cor":           46,
		"2corinthians":   47,
		"2cor":           47,
		"galatians":      48,
		"gal":            48,
		"ephesians":      49,
		"eph":            49,
		"philippians":    50,
		"phil":           50,
		"colossians":     51,
		"col":            51,
		"1thessalonians": 52,
		"1thess":         52,
		"2thessalonians": 53,
		"2thess":         53,
		"1timothy":       54,
		"1tim":           54,
		"2timothy":       55,
		"2tim":           55,
		"titus":          56,
		"philemon":       57,
		"phlm":           57,
		"hebrews":        58,
		"heb":            58,
		"james":          59,
		"jas":            59,
		"1peter":         60,
		"1pet":           60,
		"2peter":         61,
		"2pet":           61,
		"1john":          62,
		"2john":          63,
		"3john":          64,
		"jude":           65,
		"revelation":     66,
		"rev":            66,
	}
)
